steps:
# Step 1: Build Docker image and push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/sound-chimera-464005-q1/k8-repo/hello-world:latest',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/sound-chimera-464005-q1/k8-repo/hello-world:latest'
    ]

# Step 2: Authenticate and deploy to GKE
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    [
      '-c',
      'gcloud container clusters get-credentials k8-private --region us-central1 --project $PROJECT_ID && \
      kubectl apply -f k8s/deployment.yaml && \
      kubectl apply -f k8s/service.yaml'
    ]

timeout: '900s'
