serviceAccount: cloudbuild@sound-chimera-464005-q1.iam.gserviceaccount.com

logsBucket: gs://k8-bucket-07/

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud container clusters get-credentials k8-private --region us-central1 --project $PROJECT_ID
      kubectl apply -f k8s/deployment.yaml
      kubectl apply -f k8s/service.yaml

timeout: '30s'
